version: "3.1"
services:
  workbunny-rabbitmq-php:
    restart: always
    container_name: workbunny-rabbitmq-php
    build:
      context: ./
    volumes:
      - ./:/var/www
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
    tty: true

  workbunny-rabbitmq:
    restart: always
    container_name: workbunny-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    volumes:
      - ./../temp/:/var/log/rabbitmq/